version: "3"

volumes:
  db:
  bundle:
  elastic:

services:
  db:
    image: postgres:12.4
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ./node_modules:/app/node_modules
      - ./vendor/assets/fonts:/usr/share/fonts
    ports:
      - "3000:3000"
    env_file: app.env
    depends_on:
      - db
      - smtp
      - redis
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_REQUEST_TIMEOUT=300 #seconds
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "10"

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []

  redis:
    image: redis:5.0.6

  elasticsearch:
    image: elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elastic:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "10"
    ports:
      - 9200:9200

  smtp:
    image: "djfarrelly/maildev:latest"
    command: "bin/maildev --web 3080 --smtp 1025 --incoming-user smtp --incoming-pass smtp"
    ports:
      - "3080:3080"

  ngrok:
    image: wernight/ngrok
    ports:
      - 4040:4040
    environment:
      NGROK_PORT: "web:3000"
