volumes:
  postgres_data:
  bundle:

services:
  db:
    image: postgres:18.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ./vendor/assets/fonts:/usr/share/fonts
    ports:
      - '3000:3000'
    env_file: app.env
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '10'

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []

  redis:
    image: redis:7.2.3

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - web
    command: http web:3000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN} #https://ngrok.com
    ports:
      - "4040:4040"
